# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('NObs', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('LocationID', models.IntegerField()),
                ('Temperature', models.FloatField(null=True)),
                ('Pressure', models.SmallIntegerField(null=True)),
                ('Screen_Relative_Humidity', models.FloatField(null=True)),
                ('Wind_Speed', models.SmallIntegerField(null=True)),
                ('Visibility', models.SmallIntegerField(null=True)),
                ('Dew_Point', models.FloatField(null=True)),
                ('Pressure_Tendency', models.CharField(max_length=5, null=True)),
                ('Weather_Type', models.SmallIntegerField(null=True)),
                ('Wind_Direction', models.CharField(max_length=3, null=True)),
                ('Wind_Gust', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
