# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='Visibility',
            field=models.IntegerField(null=True),
        ),
    ]
